# Generated by Django 4.1 on 2022-09-10 19:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=11, unique=1)),
                ('created', models.CharField(default=' ', max_length=20)),
                ('name', models.CharField(default=' ', max_length=150)),
                ('shortname', models.CharField(default=' ', max_length=50)),
                ('objet', models.CharField(default=' ', max_length=1000)),
                ('adress1', models.CharField(default=' ', max_length=100)),
                ('adress2', models.CharField(default=' ', max_length=100)),
                ('adress', models.CharField(default=' ', max_length=100)),
                ('codepostal', models.CharField(default=' ', max_length=10)),
                ('town', models.CharField(default=' ', max_length=100)),
                ('pays', models.CharField(default=' ', max_length=100)),
                ('president', models.CharField(default='John Doh', max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('logo', models.ImageField(default='default_profile.png', upload_to='')),
                ('theme', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
            ],
        ),
        migrations.CreateModel(
            name='EventNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Pas de titre', max_length=200)),
                ('text', models.CharField(max_length=4000, unique=1)),
                ('author', models.CharField(max_length=150)),
                ('time_published', models.DateTimeField(auto_now=True)),
                ('date_event', models.DateField(default='1970-01-01')),
                ('time_event', models.TimeField()),
                ('location', models.CharField(max_length=1000)),
                ('file', models.FileField(blank=True, default=False, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, default=False, null=True, upload_to='')),
                ('participants', models.CharField(blank=True, max_length=5000)),
                ('asso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assosparents.asso')),
            ],
        ),
    ]
