# Generated by Django 4.1 on 2022-09-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assosparents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventnow',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventnow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
