# Generated by Django 4.1 on 2022-09-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assosparents', '0002_alter_eventnow_file_alter_eventnow_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventnow',
            name='participants',
        ),
    ]
