# Generated by Django 4.1 on 2022-09-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assosparents', '0003_remove_eventnow_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConseilEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('resume', models.CharField(max_length=6000)),
                ('author', models.CharField(max_length=150)),
                ('time_published', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('asso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assosparents.asso')),
            ],
        ),
    ]
