# Generated by Django 4.1 on 2022-09-13 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assosparents', '0004_conseilecole'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDurate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=4000, unique=1)),
                ('author', models.CharField(max_length=150)),
                ('time_published', models.DateTimeField(auto_now=True)),
                ('type_event', models.CharField(max_length=100)),
                ('daily', models.CharField(blank=True, max_length=50, null=True)),
                ('hebdo', models.CharField(blank=True, max_length=50, null=True)),
                ('mensually', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('asso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assosparents.asso')),
            ],
        ),
    ]
