# Generated by Django 4.1 on 2022-09-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assosparents', '0005_eventdurate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='')),
                ('link', models.URLField(blank=True, null=True)),
                ('asso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assosparents.asso')),
            ],
            options={
                'unique_together': {('entreprise', 'asso')},
            },
        ),
    ]
