# Generated by Django 4.1 on 2022-09-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assosparents', '0006_partenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='asso',
            name='minilogo',
            field=models.ImageField(default='default_profile.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='asso',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventdurate',
            name='text',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='eventnow',
            name='text',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterUniqueTogether(
            name='conseilecole',
            unique_together={('date', 'asso')},
        ),
        migrations.AlterUniqueTogether(
            name='eventdurate',
            unique_together={('title', 'text', 'asso')},
        ),
        migrations.AlterUniqueTogether(
            name='eventnow',
            unique_together={('title', 'text', 'asso')},
        ),
    ]
