# Generated by Django 4.1 on 2022-09-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assosparents', '0007_asso_minilogo_alter_asso_logo_alter_eventdurate_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='promo_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
