# Generated by Django 4.1 on 2022-09-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assosparents', '0008_partenaire_promo_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='asso',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
