# Generated by Django 4.1 on 2022-09-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assosparents', '0009_asso_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdurate',
            name='daily',
        ),
        migrations.RemoveField(
            model_name='eventdurate',
            name='hebdo',
        ),
        migrations.RemoveField(
            model_name='eventdurate',
            name='mensually',
        ),
        migrations.RemoveField(
            model_name='eventdurate',
            name='type_event',
        ),
        migrations.AddField(
            model_name='eventdurate',
            name='day',
            field=models.CharField(choices=[('LU', 'Lundi'), ('MA', 'Mardi'), ('ME', 'Mercredi'), ('JE', 'Jeudi'), ('VE', 'Vendredi'), ('SA', 'Samedi'), ('DI', 'Dimanche')], default='LU', max_length=2),
        ),
        migrations.AddField(
            model_name='eventdurate',
            name='location',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='eventdurate',
            name='time_event',
            field=models.TimeField(null=True),
        ),
    ]
