# Generated by Django 4.1 on 2022-09-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assosparents', '0012_alter_asso_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('niveau', models.CharField(choices=[('Maternelle', 'Maternelle'), ('Élémentaire', 'Elementaire'), ('Collège', 'Collège'), ('Lycée', 'Lycée')], default='Maternelle', max_length=12)),
                ('description', models.CharField(max_length=4000)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('link', models.URLField(blank=True, null=True)),
                ('asso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assosparents.asso')),
            ],
            options={
                'unique_together': {('title', 'asso')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=4000)),
                ('asso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assosparents.asso')),
            ],
            options={
                'unique_together': {('title', 'asso')},
            },
        ),
    ]
