# Generated by Django 4.1 on 2022-10-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assosparents', '0013_ressource_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
