# Generated by Django 4.1 on 2022-09-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assosparents', '0003_remove_eventnow_participants'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eventnwo',
            field=models.ManyToManyField(null=True, to='assosparents.eventnow'),
        ),
    ]
