# Generated by Django 4.1 on 2022-09-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_eventnwo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eventnwo',
            new_name='eventnow',
        ),
    ]
