# Generated by Django 4.1 on 2022-09-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_eventnwo_user_eventnow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('VISITEUR', 'Visiteur'), ('MEMBRE', 'Membre'), ('ADMINISTRATEUR', 'Administrateur'), ('PRESIDENT', 'President'), ('WEBMASTER', 'Webmaster')], max_length=30, verbose_name='Rôle'),
        ),
    ]
