# Generated by Django 4.1 on 2022-09-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assosparents', '0007_asso_minilogo_alter_asso_logo_alter_eventdurate_text_and_more'),
        ('authentication', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='asso',
            field=models.ManyToManyField(blank=True, null=True, to='assosparents.asso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='eventnow',
            field=models.ManyToManyField(blank=True, null=True, to='assosparents.eventnow'),
        ),
    ]
