# Generated by Django 4.1 on 2022-09-27 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assosparents', '0010_remove_eventdurate_daily_remove_eventdurate_hebdo_and_more'),
        ('authentication', '0006_alter_user_asso_alter_user_eventnow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveIntegerField(default=1)),
                ('asso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assosparents.asso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('asso', 'user')},
            },
        ),
    ]
