# Generated by Django 4.1 on 2022-09-27 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assosparents', '0012_alter_asso_logo'),
        ('authentication', '0007_remove_user_role_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assosparents.asso')),
                ('user_voted', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='voted_user_set', to=settings.AUTH_USER_MODEL)),
                ('user_voteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='voteur_user_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('asso', 'user_voteur')},
            },
        ),
    ]
