# Generated by Django 4.1 on 2022-09-27 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user_voted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user_voteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voteur_user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
