# Generated by Django 4.1 on 2022-09-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assosparents', '0013_ressource_message'),
        ('authentication', '0010_ressourcelike_messagevu'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagevu',
            unique_together={('message', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='ressourcelike',
            unique_together={('ressource', 'user')},
        ),
    ]
